version: "3"
services:
  demo-nodeswarm:
    image: nodeswarm:1.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - docker-demo-swarm
networks:
  docker-demo-swarm: